### ISSUE TITLE
Add user streams

### ISSUE THREAD

**Issue by arski** [dustin/twitty-twister#10]
Hi there, really great API client implementation!

Would you mind adding support for https://dev.twitter.com/docs/api/2/get/user to the master branch? Should be an easy copy paste job :)

Cheers

**Comment by ralphm** [comment]
I have been planning to work on this. Thanks for filing the ticket.

**Comment by ralphm** [comment]
Created a branch and took a first stab at this: https://github.com/ralphm/twitty-twister/tree/user-streams-10

**Comment by arski** [comment]
Hmm, I'm wondering why you decided to put the keywords directly into the function definition - e.g. filter() has actually very similar (types of) arguments, and it's just using "args" - I find that so much more convenient that I can just define whichever args I need in the proper format straight away (not splitting things into a list so that they get processed into a comma-separated string afterwards again..)

**Comment by ralphm** [comment]
@arski: right. It would be nice to have a higher level interface, but what you're saying is more consistent with what we have currently. I updated the branch to match, including an example. Does is now work for you?
PS. I could always add something later that does something smart like converting to a comma-separated string if the value for the `track` argument is a list.

**Comment by arski** [comment]
Yea, I think this is better. You can always create something like a "track" version of the "user" method which processes the list of arguments and passes them on to the "filter" method.. Anyway, looking good.

Would you mind also adding the one site stream endpoint https://dev.twitter.com/docs/streaming-apis/streams/site or would you want me to open a separate issue for that?

Thanks

**Comment by ralphm** [comment]
Since #12 has been merged, this can be closed, too.
