### ISSUE TITLE
API failing with 404

### ISSUE THREAD

**Issue by akrherz** [dustin/twitty-twister#14]
I am not the sharpest tool in the toolbox, but I think the API BASE_URL needs to be updated to:

BASE_URL="https://api.twitter.com/1"

https://dev.twitter.com/discussions/10803

my stuff broke 10 Oct without this patch.

**Comment by kracekumar** [comment]
You can pass base_url in `twitter.Twitter(self, user=None, passwd=None, base_url='https://api.twitter.com/1', search_url='http://search.twitter.com/search.atom', consumer=None, token=None, signature_method=<oauth.oauth.OAuthSignatureMethod_HMAC_SHA1 object at 0x28b2c90>, client_info=None, timeout=0)`
