### ISSUE TITLE
verify_credentials error

### ISSUE THREAD

**Issue by ga2arch** [dustin/twitty-twister#2]
the api wants a GET ( http://apiwiki.twitter.com/Twitter-REST-API-Method%3A-account%C2%A0verify_credentials ) but you always use a POST

this is the diff http://dpaste.com/hold/48159/

**Comment by ga2arch** [comment]
sorry, i have done the diff for the forked version of duglas, this is the correct diff
http://dpaste.com/hold/48162/

**Comment by ga2arch** [comment]
i have seen only now that there is a __get function
def verify_credentials(self):
        "Verify a user's credentials."
        return self.__get("/account/verify_credentials.xml", None, None)

**Comment by dustin** [comment]
Fixed in feec2b1dece2de1def53e7bca49d71aab1258d22
